Mentor-Cycle/mentor-cycle-fe

.storybook/preview.ts, src/components/Chip/Chip.stories.tsx
Nesta tarefa foi realizada a criação do Storybook do componente Chip, com os seguintes controles:
- Front-end;
- Back-end;
- FullStack.
=> feat: create chip storybook

.storybook/main.ts, .storybook/preview.ts, package.json, src/components/Button/Button.stories.tsx, src/components/Button/Button.tsx, src/components/Button/Button.types.tsx, src/pages/index.tsx, tailwind.config.js, yarn.lock
1. Updated the implementation of the "Button" component to use the props from the "ButtonProps" interface that were defined in a separate file.
2. Created a new "ButtonIcon" component to render icons within the "Button" component.
3. Updated the implementation of the "Button" component to allow for the inclusion of an icon within the button.
4. Created a new "Button.stories.tsx" file to define different variations of the "Button" component using Storybook. The different variations include primary and secondary variants, regular and small sizes, and disabled and enabled states. It also includes an example of a button with an icon using the "ButtonIcon" component.
1. Atualizada a implementação do componente "Button" para usar os props da interface "ButtonProps" que foram definidos em um …
=> feat(button): button-style

package.json, src/components/Checkbox/Checkbox-types.tsx, src/components/Checkbox/Checkbox.stories.tsx, src/components/Checkbox/Checkbox.tsx, src/components/Checkbox/Checkbox.types.ts, src/components/Checkbox/index.tsx, src/pages/index.tsx, yarn.lock
I've created a new implementation of a checkbox component called "CheckboxRadix". This component uses the libraries "@radix-ui/react-checkbox" and "react-icons/bs" to provide a custom checkbox with a check icon.
it is possible to select the checkbox with the space key according to good accessibility practices
Eu criei uma nova implementação de um componente de caixa de seleção chamado "CheckboxRadix". Este componente usa as bibliotecas "@radix-ui/react-checkbox" e "react-icons/bs" para fornecer uma caixa de seleção personalizada com um ícone de verificação.
é possível selecionar a caixa de seleção com a tecla de espaço de acordo com as boas práticas de acessibilidade
<br>
</br>
=> feat: create CheckBox component with RadixUI

cypress.config.ts, cypress/fixtures/example.json, package.json, yarn.lock
=> feat: installation cypress

src/pages/signup/plan.tsx, yarn.lock
Corrigido o botão de voltar na tela de seleção de modelo.
card: https://prnt.sc/DgYQkNQEznDH
=> fix: issue with back button on user registration screen

package.json, src/components/FormSteps/FormSteps.tsx, src/components/FormSteps/PersonalInformation.tsx, src/components/Toast/ToastComponent.stories.tsx, src/components/Toast/ToastComponent.tsx, src/pages/_app.tsx, yarn.lock
O componente ToastComponent que foi criado é um exemplo demonstrativo de como utilizar a biblioteca react-toastify para exibir notificações na tela. Este componente pode ser utilizado como base para criar outras implementações personalizadas de notificações em um projeto.
**No entanto, é importante ressaltar que, na prática, o desenvolvedor não precisa criar um componente específico para exibir as notificações.** Em vez disso, é possível utilizar a função toast diretamente da biblioteca react-toastify, como exemplificado nas funções ToastVariants no código do componente.
Para utilizar a função toast, o desenvolvedor deve importá-la do pacote react-toastify e chamá-la com o tipo de notificação desejado (success, error, warning ou info) e a mensagem a ser exibida. Por exemplo:
```
import { …
```
=> feat: toast component

src/components/MentoringWeekCard/MentoringWeekCard.stories.tsx, src/components/MentoringWeekCard/MentoringWeekCard.test.tsx, src/components/MentoringWeekCard/MentoringWeekCard.tsx, src/components/MentoringWeekCard/MentoringWeekCard.types.ts, src/components/MentoringWeekCard/index.tsx, tsconfig.json
=> feat: mentoring week card

README.md, package.json, src/components/Modal/Modal.stories.tsx, src/components/Modal/Modal.tsx, src/components/Modal/Modal.types.ts, src/components/Modal/index.tsx, src/components/NavBar/NavBar.tsx, src/components/NavBar/NavBar.types.ts, src/components/NavBar/index.tsx, src/pages/request-change-password.tsx, tailwind.config.js, yarn.lock
Foi criado o componente "modal" utilizando Radix UI.
Como o modal deverá ser utilizado em algumas partes do template, criei para ele receber "modalOpen" onde quando for utilizado o desenvolvedor podera estilizar a abertura do modal como preferir. Irá receber também um "modalTitle" obrigatório e "modalDescription" e "modalClose" como opcionais. 
Para fechar o modal, terá por padrão o icone de "X" no canto superior direito.
Segue exemplo do modal:
Storybook: O storybook foi construído apenas para mostrar o funcionamento do modal, sem estilizações pré-definidas.
=> feat: create modal component

src/components/Toggle/Toggle.stories.tsx, src/components/Toggle/Toggle.tsx, src/components/Toggle/Toggle.types.ts, src/components/Toggle/index.tsx
creating toggle button component for switch cases
=> feat: create toggle button

src/components/Chip/Chip.stories.tsx, src/components/Chip/Chip.tsx, src/components/Chip/Chip.types.ts, src/components/MentoringWeekCard/MentoringWeekCard.stories.tsx, src/components/MentoringWeekCard/MentoringWeekCard.test.tsx, src/components/MentoringWeekCard/MentoringWeekCard.tsx, src/components/MentoringWeekCard/MentoringWeekCard.types.ts
Adjust chip type in MentoringWeekCard component to receive Chip component and added new styling for chip variants
=> refactor: adjust type chips in MentoringWeekCard and add new type style

src/components/Stepper/Stepper.tsx, src/components/Stepper/Stepper.types.ts, src/pages/signup/register.tsx, yarn.lock
=> fix: bug stepper componente and add small size

.github/workflows/node.js.yml
=> chore: add storybook build pipeline

src/components/Header/Header.tsx, src/pages/signin.tsx, src/providers/auth/auth.tsx
=> fix: storage dashboard page

src/components/FormSteps/PersonalInformation.tsx, src/components/TermsAndPrivacyPopup/TermsAndPrivacyPopup.tsx, src/components/TermsAndPrivacyPopup/index.tsx, src/pages/privacy-policy.tsx, src/pages/signin.tsx, src/pages/terms.tsx
=> chore: add Terms and Privacy policy

src/components/EditProfile/EditeProfile.tsx, src/pages/profile.tsx
* Changed the styling of the Profile page description. When the user sets some information, the text will be in black and when nothing is passed, the text will be in gray.
* The Label of the button inside the modal was also changed to "Save"
=> feat: changed description page profile

src/components/Dropzone/Dropzone.tsx, src/components/EditProfile/EditeProfile.tsx, src/components/FormSteps/FormSteps.tsx, src/components/FormSteps/Profile.tsx, src/components/Header/Header.tsx, src/components/Header/ModalNotifications.tsx, src/components/Header/ModalSettings.tsx, src/components/Modal/Modal.tsx, src/hooks/useForm.ts, src/pages/_app.tsx, src/pages/dashboard/dashboard.tsx, src/pages/profile.tsx, src/pages/signup/plan.tsx, src/pages/signup/register.tsx
=> fix: bugs issues caça bugs

src/components/Button/Button.tsx, src/components/Date/Date.stories.tsx, src/components/Date/Date.types.ts, src/components/Date/InputBirthday.tsx, src/components/Date/dateHelpers.ts, src/components/Date/index.tsx, src/components/EditProfile/EditeProfile.tsx, src/components/FormSteps/ContactInformation.tsx, src/components/FormSteps/FormSteps.tsx, src/components/FormSteps/PersonalInformation.tsx, src/components/Input/Input.tsx, src/components/MultiSelect/MultiSelect.tsx, src/hooks/useForm.ts
-fix birthday input signup
-fix feedback erros signup
=> Refactor input birthday

src/components/MentorModalAvailability/MentorModalAvailability.tsx, src/pages/dashboard/dashboard.tsx, src/pages/profile.tsx
* The dashboard was changed to filter scheduled mentoring according to whether the user is a mentor or mentee.
* Added a description in the mentor's modal for scheduling mentorships and changed the default text of available time cards.
=> feat: mentoring filter and mentoring scheduling fixes

.env, .gitignore, src/components/CardProfile/CardProfile.tsx, src/components/EditProfile/EditeProfile.tsx, src/components/FormSteps/FormSteps.tsx, src/components/FormSteps/Profile.tsx, src/components/Header/Header.tsx, src/components/Header/ModalSettings.tsx, src/components/Input/Input.tsx, src/components/LocationSelector/SelectLocation.tsx, src/components/MultiSelect/SelectSkills.tsx, src/components/ScheduleMentorshipModal/ScheduleMentorhipModal.tsx, src/pages/dashboard/dashboard.tsx, src/pages/mentors/[id].tsx, src/pages/mentors/mentors.tsx, src/pages/profile.tsx, src/pages/request-change-password.tsx, src/pages/signin.tsx, src/services/apollo/apollo-client.ts, src/services/apollo/queries/queries.tsx, src/utils/utilsMentorPage.ts
=> Fix small bugs

README.md, src/components/CardNotification/CardNotification.tsx, src/components/CardNotification/CardNotification.types.ts, src/components/CardProfile/CardProfile.stories.tsx, src/components/CardProfile/CardProfile.tsx, src/components/CardProfile/CardProfile.types.ts, src/components/CardProfile/mockCard.tsx, src/components/EditProfile/EditeProfile.tsx, src/components/Header/Header.tsx, src/components/Header/ModalNotifications.tsx, src/components/Header/ModalSettings.tsx, src/components/LocationSelector/SelectLocation.tsx, src/components/Modal/Modal.tsx, src/components/MultiSelect/MultiSelect.types.ts, src/components/MultiSelect/SkillsEditProfile.tsx, src/pages/change-password.tsx, src/pages/mentors/[id].tsx, src/pages/mentors/mentors.tsx, src/pages/profile.tsx, src/services/apollo/mutations/mutations.ts
fix bugs dashboard and mentor page
=> fix: dashboard page and mentor page

src/components/Calendar/Calendar.tsx, src/components/CardProfile/CardProfile.tsx, src/components/DashboardCardProfile/DashboardCardProfile.tsx, src/components/Dropzone/Dropzone.tsx, src/components/EditProfile/EditeProfile.tsx, src/components/Header/Header.tsx, src/components/Header/ModalSettings.tsx, src/components/MentorModalAvailability/MentorModalAvailability.tsx, src/components/MentorModalAvailability/SuccessullyCreated.tsx, src/components/MentoringLinkCard/MentoringLinkCard.tsx, src/components/MentoringWeekCard/MentoringWeekCard.tsx, src/components/NavBar/MobileNavBar.tsx, src/components/NavBar/NavBar.tsx, src/components/ScheduleMentorshipModal/ScheduleMentorhipModal.tsx, src/hooks/useMentorProfile.tsx, src/pages/dashboard/dashboard.tsx, src/pages/mentors/[id].tsx, src/pages/mentors/mentors.tsx, src/pages/profile.tsx
fix layout mobile and add navbar Mobile
=> fix: layout mobile

src/components/EditProfile/EditeProfile.tsx, src/components/Header/Header.tsx, src/components/Header/ModalSettings.tsx, src/components/ProfileCardToggle/ProfileCardToggle.tsx, src/components/TermsAndPrivacyPopup/TermsAndPrivacyPopup.tsx, src/hooks/useFetch.ts, src/pages/mentors/[id].tsx, src/pages/profile.tsx, src/pages/signin.tsx, src/providers/user/AppContext.tsx, src/services/apollo/mutations/mutations.ts, src/services/apollo/queries/queries.tsx, tailwind.config.js
- fix double toast error signin
- add linkedin and github edit profile
- styling info profile page
=> fix: add linkedin and github edit profile and toast error

src/components/Button/Button.tsx, src/components/Button/Button.types.ts, src/components/EmptyValues/MentorDashboard.tsx, src/components/EmptyValues/StudentDashboard.tsx, src/components/Header/Header.tsx, src/components/ProfileCompletionAlert/ProfileCompletionAlert.tsx, src/pages/dashboard/dashboard.tsx
=> feat: profile complet alert

src/components/Header/ModalSettings.tsx, src/pages/mentors/[id].tsx
=> fix: dark mode layout

src/components/EditProfile/EditeProfile.tsx, src/config/constants.ts, src/pages/profile.tsx
[[Front-end] - Estilo do título "Agenda de mentorias"#211](https://github.com/Mentor-Cycle/mentor-cycle-fe/issues/211)
[[Front-end] - Uso de / no título do perfil#209](https://github.com/Mentor-Cycle/mentor-cycle-fe/issues/209)
[[Front-end] - Adicionar Header na tela profile#220](https://github.com/Mentor-Cycle/mentor-cycle-fe/issues/220)
=> Fix title mentoring schedule

src/components/Header/Header.tsx, src/components/NavBar/NavBar.tsx
segue as imagens dark mode black e light com dropdown abert
=> fix: dropdown dark mode

src/pages/dashboard/dashboard.tsx
=> fix: modification text Filtrar for Todas

src/components/MentoringWeekCard/MentoringWeekCard.tsx, src/components/MentoringWeekCard/renderMentoringWeekCards.tsx, src/pages/dashboard/dashboard.tsx
adjustment was made to alignment of the mentoring week cards.
=> fix: padding mentoring week card

src/components/Dropzone/Dropzone.tsx
Alteração do tamanho do texto do pop-up de confimação para alteração da foto do profile. 
&nbsp;
=> refactor: popup text size fix
